buildscript {
    repositories {
        google()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.3'
    }
}

apply plugin: 'com.android.library'
apply plugin: 'maven-publish'

android {
    namespace 'com.shockwave.pdfium'
    compileSdk 35



    sourceSets {
        main {
            jni.srcDirs = []
            jniLibs.srcDir 'src/main/libs'
        }
    }

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        minSdk 21
        targetSdk 35
        versionCode 2
        versionName "1.9.5-beta01"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

repositories {
    google()
    mavenCentral()
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}



